fruits <- c("apple", "guava", "lime", "blackberry", "raisin", "cherry", 
"strawberry", "blackberry", "fig", "cherry", "apple", "strawberry", 
"fig", "mango", "cherry", "guava", "mango", "apple", "apple", 
"blackberry", "mango", "cherry", "cherry", "fig", "strawberry", 
"cherry", "apple", "mango", "guava", "cherry", "guava", "apple", 
"mango", "blackberry", "mango", "fig", "strawberry", "blackberry", 
"raisin", "blackberry", "guava", "raisin", "mango", "lime", "cherry", 
"strawberry", "guava", "mango", "mango", "lime", "raisin", "apple", 
"mango", "cherry", "guava", "blackberry", "guava", "blackberry", 
"raisin", "blackberry", "blackberry", "lime", "mango", "mango", 
"lime", "cherry", "raisin", "cherry", "fig", "strawberry", "strawberry", 
"blackberry", "fig", "raisin", "apple", "raisin", "apple", "mango", 
"cherry", "blackberry", "mango", "guava", "apple", "fig", "apple", 
"fig", "raisin", "fig", "guava", "strawberry", "strawberry", 
"guava", "guava", "lime", "lime", "raisin", "cherry", "blackberry", 
"cherry", "cherry", "lime", "fig", "guava", "guava", "apple", 
"guava", "raisin", "lime", "raisin", "guava", "fig", "blackberry", 
"lime", "mango", "raisin", "blackberry", "mango", "guava", "raisin", 
"fig", "fig", "blackberry", "raisin", "cherry", "fig", "fig", 
"strawberry", "blackberry", "blackberry", "strawberry", "lime", 
"lime", "lime", "blackberry", "fig", "guava", "raisin", "raisin", 
"cherry", "apple", "blackberry", "strawberry", "blackberry", 
"cherry", "lime", "apple", "fig", "lime", "blackberry", "guava", 
"apple", "guava", "apple", "guava", "fig", "lime", "fig", "blackberry", 
"cherry", "fig", "raisin", "blackberry", "apple", "fig", "strawberry", 
"raisin", "mango", "lime", "fig", "fig", "cherry", "lime", "mango", 
"strawberry", "lime", "blackberry", "lime", "lime", "blackberry", 
"raisin", "cherry", "blackberry", "guava", "lime", "cherry", 
"guava", "raisin", "mango", "mango", "strawberry", "fig", "apple", 
"apple", "mango", "lime", "mango", "raisin", "blackberry", "blackberry", 
"apple", "guava", "lime", "mango", "lime", "cherry", "blackberry", 
"fig", "apple", "strawberry", "mango", "raisin", "apple", "strawberry", 
"lime", "blackberry", "fig", "guava", "guava", "strawberry", 
"fig", "fig", "blackberry", "apple", "lime", "cherry", "cherry", 
"cherry", "strawberry", "raisin", "mango", "fig", "mango", "blackberry", 
"strawberry", "mango", "lime", "mango", "fig", "cherry", "fig", 
"guava", "raisin", "cherry", "cherry", "raisin", "raisin", "strawberry", 
"mango", "apple", "strawberry")
